### ISSUE TITLE
System.OverflowException When Accessing ImageMagick.IptcProfile.Values

### ISSUE THREAD

**Issue by aaronmbos** [dlemstra/Magick.NET#1031]
### Description
A `System.OverflowException` is being thrown when accessing the `ImageMagick.IptcProfile.Values` property. I can confirm that the exception also occurs when invoking `IptcProfile.GetAllValues` and `IptcProfile.GetValue`.

### Steps to Reproduce

**Unfortunately I cannot provide a link to an image that will reproduce this exception along with this issue. I would be able to share the image(s) in a non-public manner (via DM, email, etc.)**
```
using ImageMagick;
using System;
class Program
{
    static void Main(string[] args)
    {
        private static readonly string _testImagePath = @".\path-to-image.jpg";
        using (var img = new MagickImage(_testImagePath))
        {
            var iptcProf = img.GetIptcProfile();
            foreach (var prop in iptcProf.Values) // Exception occurs here
            {
                Console.WriteLine($"{prop.Tag}: {prop.Value}");
            }
        }
    }
}
```
Exception Message: `Value was either too large or too small for a UInt16.`
Stack Trace:
```
   at System.Convert.ToUInt16(Int32 value)
   at System.Int32.System.IConvertible.ToUInt16(IFormatProvider provider)
   at System.Convert.ToUInt16(Object value, IFormatProvider provider)
   at System.Enum.System.IConvertible.ToUInt16(IFormatProvider provider)
   at ImageMagick.EnumHelper.Parse[TEnum](UInt16 value, TEnum defaultValue) in /_/src/Shared/EnumHelper.cs:line 81
   at ImageMagick.IptcProfile.Initialize() in /_/src/Magick.NET.Core/Profiles/Iptc/IptcProfile.cs:line 257
   at ImageMagick.IptcProfile.get_Values() in /_/src/Magick.NET.Core/Profiles/Iptc/IptcProfile.cs:line 63
   at ImageProcessingConsole4_6_1.Program.Main(String[] args) in source\repos\ImageProcessingConsole4_6_1\ImageProcessingConsole4_6_1\Program.cs:line 21
```

### System Configuration
The code is running in a .NET Framework 4.6.1 Console application on an x64 Windows 10 machine.

- Magick.NET version: Magick.NET-Q16-AnyCpu v8.3.1
- Environment (Operating system, version and so on): Windows 10 build 19042.1165 x64
- Additional information:

**Comment by aaronmbos** [comment]
While continuing to examine the stack trace, the exception appears to be occurring when trying to parse a potentially unknown IPTC tag/value.

`at ImageMagick.IptcProfile.Initialize() in /_/src/Magick.NET.Core/Profiles/Iptc/IptcProfile.cs:line 257`

https://github.com/dlemstra/Magick.NET/blob/6d0ae288a279e9f86a50729205210c083fdfc9e6/src/Magick.NET.Core/Profiles/Iptc/IptcProfile.cs#L257

In the `EnumHelper.Parse` method, the call to `ToUInt16` most likely fails while iterating the IPTC tags because `IptcTag.Unknown = -1`, which is smaller than the MinValue for ushort.

https://github.com/dlemstra/Magick.NET/blob/6d0ae288a279e9f86a50729205210c083fdfc9e6/src/Shared/EnumHelper.cs#L83

Would it be possible to use `UInt16.TryParse` here instead?

**Comment by dlemstra** [comment]
Thanks for reporting this and pointing me to the area that has a problem. I just pushed a fix for this and it will be resolved in the next release.
