### ISSUE TITLE
JPEG XL: "unable to read image data" on certain files

### ISSUE THREAD

**Issue by VcSaJen** [dlemstra/Magick.NET#1049]
### Description

Trying to open https://github.com/libjxl/conformance/blob/9485afaacfc575aa233f2a15051d808a44b9f900/testcases/opsin_inverse/input.jxl?raw=true JXL file from conformance tests, results in MagickCorruptImageErrorException exception.

### Steps to Reproduce

```
ImageMagick.MagickCorruptImageErrorException: unable to read image data `' @ error/jxl.c/ReadJXLImage/426
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /_/src/Magick.NET/Native/NativeInstance.cs:line 57
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(IMagickSettings`1 settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller) in /_/src/Magick.NET/Native/MagickImage.cs:line 5386
   at ImageMagick.MagickImage.Read(Stream stream, IMagickReadSettings`1 readSettings, Boolean ping) in /_/src/Magick.NET/MagickImage.cs:line 7241

```

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU 8.3.2
- Environment (Operating system, version and so on): Windows 10 Pro x64 (10.0.19043.0), Runtime .NET 5.0.10 x64

- Additional information:

**Comment by dlemstra** [comment]
We are using version `0.5` of jpegxl and it looks like there was a bug fix recently that fixed this problem: https://github.com/libjxl/libjxl/issues/584. We will need to wait for the `0.6` release before we can probably read this file.

**Comment by dlemstra** [comment]
Version `0.6` has just been released and it looks like this file still doesn't seem to work.

**Comment by dlemstra** [comment]
Going to close this issue as we will need to wait for the maintainers of jxl to resolve this.
