### ISSUE TITLE
Unable to use Montage on mac OSX due to missing Helvetica font

### ISSUE THREAD

**Issue by richardlalancetteyoui** [dlemstra/Magick.NET#1074]
### Description
While attempting to use Github actions, an error showed up with missing Helvetica in unit tests.

### Steps to Reproduce
```
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Tools;
using Xunit;

namespace Tests
{
    public class ImagesReferenceTrackerTests
    {
        [Fact]
        public void ImageTracker_ProcessImages_ReturnsUsedAndUnusedImagesCorrectly()
        {
            // Arrange
            Tracker tracker = new Tracker();
            var testFolder = Directory.GetCurrentDirectory() + "/TestData/AE/";

            // Act
            tracker.ProcessImages(testFolder);
            tracker.ParallelTask.GetAwaiter().GetResult();
            IEnumerable<ImageInformation> usedImageFiles = tracker.GetUsedImageFiles();
            IEnumerable<ImageInformation> unusedImageFiles = tracker.GetUnusedImageFiles();

            // Assert
            Assert.True(usedImageFiles.Count() == 6);
            Assert.True(unusedImageFiles.Count() == 10);
            Assert.True(tracker.ResultList.Count == 16);
        }
    }
}

Build failure
  Error Message:
   ImageMagick.MagickTypeErrorException : UnableToReadFont `helvetica' @ error/annotate.c/RenderFreetype/1459
  Stack Trace:
     at ImageMagick.MagickImageCollection.NativeMagickImageCollection.Montage(IMagickImage image, IMontageSettings`1 settings) in /_/src/Magick.NET/Native/MagickImageCollection.cs:line 397
   at ImageMagick.MagickImageCollection.Montage(IMontageSettings`1 settings) in /_/src/Magick.NET/MagickImageCollection.cs:line 707
   at Tools.NinepatchProcessor.ProcessDirection(Direction direction, MagickImage image, List`1 markers) in /home/runner/work/DW-Hub/DW-Hub/DWNexus/src/Tools/NinepatchProcessor.cs:line 137
   at Tools.NinepatchProcessor.<>c__DisplayClass6_0.<ConvertPngToNinepatchWithScanningAlgorithm>b__0() in /home/runner/work/DW-Hub/DW-Hub/DWNexus/src/Tools/NinepatchProcessor.cs:line 51
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tests.NinepatchifierTests.Ninepatchifier_ProcessSimpleNinepatch_Correctly(String input, String output) in /home/runner/work/DW-Hub/DW-Hub/DWNexus/src/Tests/NinepatchifierTests.cs:line 26
  Failed Tests.NinepatchifierTests.Ninepatchifier_ProcessSimpleNinepatch_Correctly(input: "a9p_09_11_00061.png", output: "a9p_09_11_00061.9.png") [12 ms]
```     
     

### System Configuration
Using github action, ubuntu-latest. Note that my build needs to work on macos and windows also.

- Magick.NET version: Q8-AnyCPU-8.4.0
- Environment (Operating system, version and so on): ubuntu-latest, windows 10, macosx
- Additional information: I was wondering if it is possible to swap the helvetica font for a font that is universal on all the platforms?

**Comment by richardlalancetteyoui** [comment]
ok, this is actually little worst then I thought.
I can't run Montage on OSX at all. Works on windows 10 only.
So not related to tests, but the montage operation that requires a Font.
I actually don't even need to label feature, so why would it require a font loaded?

**Comment by dlemstra** [comment]
I don't see your using Montage in your code example. But I guess the `Font` of the `MontageSettings` is being used. You can also specify a filename of the font instead of the name of font. And do you have `fontconfig` installed on your OSX machine? This is used on that operating system.

**Comment by richardlalancetteyoui** [comment]
Unfortunately, fontconfig can't be used, since my application is distributed to end users (Designers)
This is on Mac.
What would be the level of effort to use a cross platform font that is already installed on all targets of .net 6.0?

**Comment by richardlalancetteyoui** [comment]
Montage is called from `ProcessImages`
I have removed Montage and used another technique to glue the images together for now.

**Comment by richardlalancetteyoui** [comment]
This still leaves montage or any other font operation unusable on Mac without a special setup, which isn't great if we are distributing our applications to end users.

**Comment by dlemstra** [comment]
I am sorry about the late reply.

> What would be the level of effort to use a cross platform font that is already installed on all targets of .net 6.0?

There is no cross platform font that is already installed on all targets of .NET. And to find that font on macOS the fontconfig library is used. My advice would be to bundle a font with your application and specify the font as a path to the font file.
