### ISSUE TITLE
Failure to build: ImageMagick DLL Depedency in OmniBlade

### ISSUE THREAD

**Issue by MarkNais** [dlemstra/Magick.NET#1099]
## Description

Per the title, OmniBlade and Nu.Gaia are failing to build, missing proper referencing to ImageMagick.
I'm not learned on lib-referencing best-practices for multi-project repositories like this one. I'm just a code experimenter on my spare time.

## Steps to Reproduce

1. Clone repo at 8340c01dec24d49d40eed62e2ae381e6a097079b
2. Open Nu.sln in Visual Studios 2022 (Community)
3. Build `Nu.Gaia` 
4. Building fails during `Omniblade` , see `Output` below.

## Triage Notes
Note: Nu.Gaia seems to have a reference to UserProject, which in turn seems to have a reference to Omniblade — if I'm reading things right. Not sure if that's intentional.

I read through #235 , and https://github.com/bryanedds/Nu/issues/235#issuecomment-506421910  - no change in behavior.

Lame workaround: pasting `Magick.NET-Q8-x64.Native.dll` into `.Nu\Projects\OmniBlade\bin\Debug` allowed building.

### System Configuration
Freshly installed VS-2022 today (and uninstalled VS-2019). Running windows 10. 

### Output / Stack Trace
```Rebuild started...
1>------ Rebuild All started: Project: Nu.Math, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: Nu.AStar, Configuration: Debug x64 ------
3>------ Rebuild All started: Project: Nu.Gaia.Design, Configuration: Debug x64 ------
1>  Nu.Math -> C:\Users\MarkN\source\repos\Nu\Nu\Nu.Math\bin\x64\Debug\Nu.Math.dll
2>  Nu.AStar -> C:\Users\MarkN\source\repos\Nu\Nu\Nu.AStar\bin\x64\Debug\Nu.AStar.dll
4>------ Rebuild All started: Project: Nu (Nu\Nu), Configuration: Debug x64 ------
3>  Nu.Gaia.Design -> C:\Users\MarkN\source\repos\Nu\Nu\Nu.Gaia.Design\bin\x64\Debug\Nu.Gaia.Design.exe
4>		Nu -> C:\Users\MarkN\source\repos\Nu\Nu\Nu\bin\Debug\Nu.exe
5>------ Rebuild All started: Project: Nu.Pipe, Configuration: Debug x64 ------
5>		Nu.Pipe -> C:\Users\MarkN\source\repos\Nu\Nu\Nu.Pipe\bin\Debug\Nu.Pipe.exe
6>------ Rebuild All started: Project: UserProject, Configuration: Debug x64 ------
7>------ Rebuild All started: Project: OmniBlade, Configuration: Debug x64 ------
8>------ Rebuild All started: Project: Nu.Template, Configuration: Debug x64 ------
8>		Nu.Template -> C:\Users\MarkN\source\repos\Nu\Nu\Nu.Template\bin\Debug\$safeprojectname$.exe
8>		"C:\Users\MarkN\source\repos\Nu\Nu\Nu.Template\..\..\Nu\Nu.Pipe\bin\Debug\Nu.Pipe.exe" "C:\Users\MarkN\source\repos\Nu\Nu\Nu.Template\\" "C:\Users\MarkN\source\repos\Nu\Nu\Nu.Template\bin\Debug\\" "C:\Users\MarkN\source\repos\Nu\Nu\Nu.Template\refinement" False
6>		UserProject -> C:\Users\MarkN\source\repos\Nu\Projects\UserProject\bin\Debug\UserProject.exe
6>		"C:\Users\MarkN\source\repos\Nu\Projects\UserProject\..\..\Nu\Nu.Pipe\bin\Debug\Nu.Pipe.exe" "C:\Users\MarkN\source\repos\Nu\Projects\UserProject\\" "C:\Users\MarkN\source\repos\Nu\Projects\UserProject\bin\Debug\\" "C:\Users\MarkN\source\repos\Nu\Projects\UserProject\refinement" False
7>		OmniBlade -> C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\bin\Debug\OmniBlade.exe
7>		"C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\..\..\Nu\Nu.Pipe\bin\Debug\Nu.Pipe.exe" "C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\\" "C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\bin\Debug\\" "C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\refinement" False
7>		Unhandled Exception: System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q8-x64.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
7>		   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
7>		   at ImageMagick.Environment.Initialize()
7>		   at ImageMagick.MagickSettings.NativeMagickSettings..cctor()
7>		   --- End of inner exception stack trace ---
7>		   at ImageMagick.MagickSettings.NativeMagickSettings..ctor()
7>		   at ImageMagick.MagickSettings..ctor()
7>		   at ImageMagick.MagickImage..ctor()
7>		   at ImageMagick.MagickImage..ctor(String fileName)
7>		   at Nu.AssetGraphModule.refineAssetOnce(String intermediateFileSubpath, String intermediateDirectory, String refinementDirectory, Refinement refinement) in C:\Users\MarkN\source\repos\Nu\Nu\Nu\AssetGraph.fs:line 191
7>		   at Nu.AssetGraphModule.refineAsset@204-1.Invoke(Refinement refinement) in C:\Users\MarkN\source\repos\Nu\Nu\Nu\AssetGraph.fs:line 205
7>		   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
7>		   at Nu.AssetGraphModule.refineAsset(String inputFileSubpath, String inputDirectory, String refinementDirectory, FSharpList`1 refinements) in C:\Users\MarkN\source\repos\Nu\Nu\Nu\AssetGraph.fs:line 203
7>		   at Nu.AssetGraphModule.buildAssets5[a](String inputDirectory, String outputDirectory, String refinementDirectory, Boolean fullBuild, IEnumerable`1 assets) in C:\Users\MarkN\source\repos\Nu\Nu\Nu\AssetGraph.fs:line 233
7>		   at Nu.AssetGraphModule.buildAssets(String inputDirectory, String outputDirectory, String refinementDirectory, Boolean fullBuild, AssetGraph assetGraph) in C:\Users\MarkN\source\repos\Nu\Nu\Nu\AssetGraph.fs:line 322
7>		   at NuPipe.Program.main(String[] argv) in C:\Users\MarkN\source\repos\Nu\Nu\Nu.Pipe\Program.fs:line 13
7>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5710,5): error MSB3073: The command ""C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\..\..\Nu\Nu.Pipe\bin\Debug\Nu.Pipe.exe" "C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\\" "C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\bin\Debug\\" "C:\Users\MarkN\source\repos\Nu\Projects\OmniBlade\refinement" False" exited with code -532462766.
7>Done building project "OmniBlade.fsproj" -- FAILED.
7>
7>Build FAILED.
9>------ Rebuild All started: Project: Nu.Gaia, Configuration: Debug x64 ------
9>		Nu.Gaia -> C:\Users\MarkN\source\repos\Nu\Nu\Nu.Gaia\bin\Debug\Nu.Gaia.exe
9>		"C:\Users\MarkN\source\repos\Nu\Nu\Nu.Gaia\..\Nu.Pipe\bin\Debug\Nu.Pipe.exe" "C:\Users\MarkN\source\repos\Nu\Nu\Nu.Gaia\\" "C:\Users\MarkN\source\repos\Nu\Nu\Nu.Gaia\bin\Debug\\" "C:\Users\MarkN\source\repos\Nu\Nu\Nu.Gaia\refinement" False
========== Rebuild All: 8 succeeded, 1 failed, 0 skipped ==========```

**Comment by MarkNais** [comment]
Posted in the wrong repo! Note to self: Don't triage at midnight.

Sorry!
