### ISSUE TITLE
MagickMissingDelegateErrorException when resizing HEIC files

### ISSUE THREAD

**Issue by omidontop** [dlemstra/Magick.NET#1105]
### Description
When resizing HEIC files, the following exception is thrown:

```
xImageMagick.MagickMissingDelegateErrorException: no encode delegate for this image format `HEIC' @ error/constitute.c/WriteImage/1276
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:line 18
   at ImageMagick.NativeHelper.CheckException(IntPtr exception) in /_/src/Magick.NET/Native/NativeHelper.cs:line 27
   at ImageMagick.MagickImage.NativeMagickImage.WriteStream(IMagickSettings`1 settings, ReadWriteStreamDelegate writer, SeekStreamDelegate seeker, TellStreamDelegate teller, ReadWriteStreamDelegate reader) in /_/src/Magick.NET/Native/MagickImage.cs:line 6661
   at ImageMagick.MagickImage.Write(Stream stream) in /_/src/Magick.NET/MagickImage.cs:line 6843
   at ImageMagick.MagickImage.ToByteArray() in /_/src/Magick.NET/MagickImage.cs:line 6395
   at .../PhotoFile.cs:line 134]
```

### Steps to Reproduce

```
using (var image = new MagickImage(path))
{
  var size = new MagickGeometry(width, height)
  {
     IgnoreAspectRatio = false,
     FillArea = true
  };

  try
  {
     image.AutoOrient();
     image.Thumbnail(size);
     image.Extent(size, Gravity.Center);
     output = image.ToByteArray();
  }
  catch (Exception e)
  {
     Debug.Write(e.ToString());
  }
}
```

Note that I have tried installing `libheif` by running: `brew install libheif` but the error remains.

### System Configuration

- Magick.NET version: 8.5.0
- Environment (Operating system, version and so on): macOS 12.0.1
- Additional information: Intel x64 CPU

**Comment by dlemstra** [comment]
The heif library is build without support for encoding `HEIC` files in Magick.NET. You can only read HEIC files with the library. We do have support for encoding images in `AVIF`.

**Comment by omidontop** [comment]
Thanks @dlemstra! That was extremely helpful. In that case I can just convert the format to Jpeg and then attempt to resize the image:

```
image.Format = MagickFormat.Jpeg;
image.AutoOrient();
image.Thumbnail(size);
image.Extent(size, Gravity.Center);
output = image.ToByteArray();

```
