### ISSUE TITLE
Unsupported file format when reading some, but not all, DNG files

### ISSUE THREAD

**Issue by neilgd** [dlemstra/Magick.NET#1131]
### Description
Cannot read *some* DNG files produced by Adobe Lightroom - throws a _Unsupported file format or not RAW_ file exception

### Steps to Reproduce
I'm reading the file into a byte array, and then this:

```
using var image = new MagickImage(bytes, MagickFormat.Dng)
```
Here is one file that doesn't work:
https://www.dropbox.com/s/xih4se5hw0fq8m8/IMG_3970.dng?dl=0

Here is the stack trace:

```
ImageMagick.MagickCoderErrorException: Unsupported file format or not RAW file `C:/Users/neil/AppData/Local/Temp/magick-d_r5KQRZk0CmW1EPHdCSlr9PeuFh4YHc' @ error/dng.c/ReadDNGImage/480
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /_/src/Magick.NET/Native/NativeInstance.cs:line 63
   at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(IMagickSettings`1 settings, Byte[] data, Int32 offset, Int32 length) in /_/src/Magick.NET/Native/MagickImage.cs:line 7100
   at ImageMagick.MagickImage.Read(Byte[] data, Int32 offset, Int32 length, IMagickReadSettings`1 readSettings, Boolean ping) in /_/src/Magick.NET/MagickImage.cs:line 7218
   at ImageMagick.MagickImage.Read(Byte[] data, MagickFormat format) in /_/src/Magick.NET/MagickImage.cs:line 4949
 ```

### System Configuration
Q16 Any CPU 9.1.2
Windows 11, .NET 5

**Comment by neilgd** [comment]
This might be related to this:

https://www.libraw.org/node/2596

**Comment by dlemstra** [comment]
Attaching image for future reference: [IMG_3970.zip](https://github.com/dlemstra/Magick.NET/files/8064243/IMG_3970.zip)

**Comment by dlemstra** [comment]
Thank for the link to that post on the libraw site. It turns out that this is not caused by the `USE_ZLIB` option but by the `USE_JPEG` option. Apparently that `.dng` file is compressed with lossy (JPEG) compression. I will need to think and read about this option to see if we can enable this inside ImageMagick.

**Comment by dlemstra** [comment]
The next release of Magick.NET will be able to read this file. I decided to add enable both the `zlib` and the `jpeg` option.

**Comment by neilgd** [comment]
Thank you!! I have no idea why Lightroom was compressing those files that way. It certainly shouldn't have been - it doesn't even have the option for it.
