### ISSUE TITLE
Unsupported file formats when reading some .ARW files

### ISSUE THREAD

**Issue by ngdph** [dlemstra/Magick.NET#1187]
### Magick.NET version

Q8-AnyCPU 11.1.2

### Environment (Operating system, version and so on)

Windows 11, .NET 4.8.04161

### Description

Cannot read some .ARW files, the program throws `Unsupported file format or not RAW file` exception

### Steps to Reproduce

I read the image by its path using this code:
`var image = new MagickImage(inputFilePath, new MagickReadSettings(){});`

I uploaded some samples: [https://www.dropbox.com/sh/62ou5c3sfzzjgol/AADNKPbblzqf7axf7uHqL7vda?dl=0](https://www.dropbox.com/sh/62ou5c3sfzzjgol/AADNKPbblzqf7axf7uHqL7vda?dl=0)

Here is the output:

> ImageMagick.MagickCoderErrorException: Unsupported file format or not RAW file `E:\Samples\Failed\DSC00004.ARW' @ error/dng.c/ReadDNGImage/494
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /_/src/Magick.NET/Native/NativeInstance.cs:line 57
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings`1 settings) in /_/src/Magick.NET/Native/MagickImage.cs:line 7159
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings, Boolean ping) in /_/src/Magick.NET/MagickImage.cs:line 7305
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings) in /_/src/Magick.NET/MagickImage.cs:line 5102
   at ImageMagick.MagickImage..ctor(String fileName, IMagickReadSettings`1 readSettings) in /_/src/Magick.NET/MagickImage.cs:line 219
   at Stdio.Pages.SingleFileConverter.<>c__DisplayClass12_0.<LoadImage>b__1()

**Comment by dlemstra** [comment]
It appears that these files are not supported by the library (libraw) that is being used to read those images. It might work in the future but it is not supported now.

**Comment by ngdph** [comment]
Hi @dlemstra 

Thanks for your reply, what can we do to support you to contribute for our community?
