### ISSUE TITLE
MagickImageCollection.Flatten on TIFF Image - Error - Improper Image Header

### ISSUE THREAD

**Issue by tenderlovingzulu** [dlemstra/Magick.NET#1200]
### Magick.NET version

Magick.NET-Q16-AnyCPU Version 11.10 and up

### Environment (Operating system, version and so on)

Windows 10 Pro Version 10.0.19043 Build 19043

### Description

I receive an "improper image header" error message when flattening a multi-layered TIFF image (see below). I then downgraded to v.9.0.0. I re-ran my code, upgraded to the next version, and repeated the process, until I discovered the error is generated in all versions starting at 11.1.0. Another discovery: when there are 2 or more masking channels, the error is triggered, BUT when there is only 1 masking channel, the file flattens successfully. (This might point to where in the code this bug was introduced.)

SOURCE TIFF TEST FILE (file too large to attach here)
----------------------------------------------------------

[https://vrxwestus.blob.core.windows.net/vrxstudios-downloads/layered.tif]

ERROR MESSAGE
-------------------

ImageMagick.MagickCorruptImageErrorException
  HResult=0x80131500
  Message=improper image header `[path-to-tiff-file]' @ error/psd.c/ReadPSDLayersInternal/2021
  Source=Magick.NET-Q16-AnyCPU
  StackTrace:
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadFile(IMagickSettings`1 settings)
   at ImageMagick.MagickImageCollection..ctor(String fileName)
   at Program.<Main>$(String[] args) in [path-to-program.cs]:line 10

CODE
------

using (MagickImage img = new MagickImageCollection("[path-to-tiff-file]").Flatten())
{
	img.Depth = 8;
	img.Settings.Compression = CompressionMethod.LZW;
	img.RemoveProfile("8bim");
	img.RemoveProfile("psd:additional-info");
	img.HasAlpha = false;
	img.Label = "Background";
	img.Write(Path.Combine([path-to-tiff-file-flattened]));
}

### Steps to Reproduce

1. Created a .NET 6.0 console app in VS 2022 Community
2. Started with Magick.NET-Q16-AnyCPU Version 9.0.0.
3. Ran the above code.
4. Upgraded to the next version of Magick.NET.
5. Repeat steps 3 and 4 for every version up to the current version (at the writing of this issue, this was 11.2.0).

**Comment by dlemstra** [comment]
This is related to ImageMagick adding support for more channels in the TIFF image format. This broke reading the (PSD) layers and I added a patch to resolve this in the next release of Magick.NET.
