### ISSUE TITLE
Unable to load shared library 'Magick.Native-Q8-arm64.dll' or one of its dependencies

### ISSUE THREAD

**Issue by omidontop** [dlemstra/Magick.NET#1271]
### Magick.NET version

12.0.1

### Environment (Operating system, version and so on)

MacOS/arm64

### Description

I have even added the extra property below but to no avail:

```xml
<MagickCopyNativeMacOS>true</MagickCopyNativeMacOS>
```

Here's the full stack trace:

```c#
MyProject.Services.ScannerService: Debug: System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q8-arm64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMagick.Native-Q8-arm64.dll, 0x0001): tried: 'libMagick.Native-Q8-arm64.dll' (no such file), '/usr/local/lib/libMagick.Native-Q8-arm64.dll' (no such file), '/usr/lib/libMagick.Native-Q8-arm64.dll' (no such file), '/Users/omidontop/Projects/media-curator/libMagick.Native-Q8-arm64.dll' (no such file)
   at ImageMagick.Environment.NativeMethods.ARM64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 53
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 18
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 321
   --- End of inner exception stack trace ---
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 343
   at ImageMagick.MagickSettings..ctor() in /_/src/Magick.NET/Settings/MagickSettings.cs:line 33
   at ImageMagick.MagickImage..ctor() in /_/src/Magick.NET/MagickImage.cs:line 41
   at ImageMagick.MagickImage..ctor(String fileName) in /_/src/Magick.NET/MagickImage.cs:line 198

```

### Steps to Reproduce

```c#
         using (var image = new MagickImage(path))
         {
            try
            {
               return image.GetExifProfile();
            }
            catch (Exception e)
            {
               Logger.LogDebug("Failed To Retrieve Exif Profile For: {}, Because: {}", path, e.Message);
            }
         }
```

**Comment by dlemstra** [comment]
Arm64 on MacOS not yet supported: #1000. But someone is now working on this here: https://github.com/dlemstra/Magick.Native/pull/23.

**Comment by omidontop** [comment]
Thanks @dlemstra!
