### ISSUE TITLE
CentOS 7 - Unable to load shared library 'Magick.Native-Q8-x64.dll'

### ISSUE THREAD

**Issue by cppmyjob** [dlemstra/Magick.NET#1278]
### Magick.NET version

Magick.NET-Q8-AnyCPU (12.2.0)

### Environment (Operating system, version and so on)

CentOS Linux release 7.9.2009 (Core), x64; dotnet 6.0.401

### Description

I am getting

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'NativeMagickColor' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q8-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMagick.Native-Q8-x64.dll: cannot open shared object file: No such file or directory
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 65
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 21
   at ImageMagick.MagickColor.NativeMagickColor..cctor() in /_/src/Magick.NET/Native/Colors/MagickColor.cs:line 156
   --- End of inner exception stack trace ---
   at ImageMagick.MagickColor.NativeMagickColor..ctor() in /_/src/Magick.NET/Native/Colors/MagickColor.cs:line 178
   at ImageMagick.MagickColor..ctor(String color) in /_/src/Magick.NET/Colors/MagickColor.cs:line 136
   at Program.<Main>$(String[] args) in /root/TestMagick/TestMagick/Program.cs:line 4
```

after launching my test app (look bellow)

### Steps to Reproduce

1. Create a new .Net 6 console app
2. Add Magick.NET-Q8-AnyCPU (12.2.0) package
3. Add the following code to Program.cs
```
using ImageMagick;
using static System.Net.Mime.MediaTypeNames;

using var image = new MagickImage(new MagickColor("black"), 1024, 1024);
new Drawables()
    // Draw text on the image
    .FontPointSize(72)
    .StrokeColor(new MagickColor("yellow"))
    .FillColor(MagickColors.Orange)
    .TextAlignment(TextAlignment.Center)
    .Text(512, 512, "Hello world")
    // Add an ellipse
    .StrokeColor(new MagickColor(0, Quantum.Max, 0))
    .FillColor(MagickColors.SaddleBrown)
    .Ellipse(256, 96, 192, 8, 0, 360)
    .Draw(image);

image.Write("1.png", MagickFormat.Png);
```

5. Build (dotnet build TestMagick.csproj) (You can build in another OS or in CentOS directly)
6. Launch the app
7. You will get the above exception

PS
1. Output build folder already has native Magick.Native-Q8-x64.dll.so 
2.  dotnet build TestMagick.csproj --arch x64 did not help (the same with other environment build keys)
3. The above example works fine on ubuntu and windows 10

**Comment by dlemstra** [comment]
I suspect that this library is not compatible with CentOS 7. I think you will get some error message when you do `ldd Magick.Native-Q8-x64.dll.so`.

**Comment by cppmyjob** [comment]
I got

```
./Magick.Native-Q8-x64.dll.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./Magick.Native-Q8-x64.dll.so)
./Magick.Native-Q8-x64.dll.so: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./Magick.Native-Q8-x64.dll.so)
./Magick.Native-Q8-x64.dll.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./Magick.Native-Q8-x64.dll.so)
        linux-vdso.so.1 =>  (0x00007ffc991f1000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f27a1d14000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f27a1af8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f27a17f6000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f27a1428000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f27a481a000)
```

after `ldd Magick.Native-Q8-x64.dll.so`
Looks like it's something is wrong with GLIBC I will dig more.
Thank you

**Comment by rkm** [comment]
Hi, were you able to find a fix for this @cppmyjob ?

**Comment by dlemstra** [comment]
Those `GLIBC_` error message should be resolved with the latest releases. Can you please open a new discussion @rkm if you are running into something similar.

**Comment by cppmyjob** [comment]
@rkm No. The issue was on Jenkins during running our tests. We made a workaround - ran our tests using docker
