### ISSUE TITLE
Fontconfig error: Cannot load default config file , Ubuntu Server

### ISSUE THREAD

**Issue by fastfoot** [dlemstra/Magick.NET#1353]
### Magick.NET version

Magick.NET-Q8-x64 12.3.0

### Environment (Operating system, version and so on)

Linux Ubuntu 22 LTS Server, no GUI

### Description

Fontconfig error: Cannot load default config file

1.
I'm looking for a way to explicitly load specific font files. 
In an IoT project it would be most convenient to deploy fonts built into the project, 

2.
In the given Ubuntu version, with **fontconfig** and **msttcorefonts** packages installed, still cannot get rid of the font config file loading error 

It would be nice if the description in the documentation was updated with such use cases. There seems to be a lack of topics in the documentation that are "obvious" to the authors, but not everyone knows what magic happens in native libs...

### Steps to Reproduce

```
using ImageMagick;

namespace MagickNETFontTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            MagickNET.Initialize();
            //MagickNET.SetFontConfigDirectory(@"/etc/fonts");
            MagickNET.SetDefaultFontFile(@"/usr/local/share/fonts/OverPass/OverpassMono-Light.ttf");
            using (var image = new MagickImage(new MagickColor("#000000"), 400, 88))
            {
                new Drawables()
                  // Draw text on the image
                  .DisableTextAntialias()
                  .FontPointSize(32)
                  .StrokeColor(MagickColors.White)
                  .FillColor(MagickColors.White)
                  .TextAlignment(TextAlignment.Left)
                  .Font("OverpassMono")
                  .Text(16, 32, "OverpassMono")
                  .StrokeColor(MagickColors.Red)
                  .FillColor(MagickColors.Red)
                  .Font("Courier")
                  .Text(16, 64, "Courier")
                  .StrokeColor(MagickColors.Yellow)
                  .FillColor(MagickColors.Yellow)
                  .Font("Arial")
                  .Text(16, 64, "Arial")
                  .Draw(image);


                image.Write(@"imagewithtext.png");
            }
        }
    }
}

```

**Comment by dlemstra** [comment]
Is it possible to create a project with a Dockerfile that demonstrates your issue?

**Comment by fastfoot** [comment]
I'm a bit confused because an error message appears to load the fontconfig file, but the font list contains some items. On the other hand, calling the Font() function with a name from this list does not change the appearance of the print.

![image](https://user-images.githubusercontent.com/34970893/222382038-9b0ddc33-9936-4bf1-9579-165a5db6f52e.png)

Fontconfig error: Cannot load default config file
Font: Andale Mono
Font: Arial
Font: Arial Black
Font: Comic Sans MS
Font: Courier New
Font: DejaVu Sans
Font: DejaVu Sans Mono
Font: DejaVu Serif
Font: DejaVu Math TeX Gyre
Font: Georgia
Font: Impact
Font: Liberation Mono
Font: Liberation Sans
Font: Liberation Sans Narrow
Font: Liberation Serif
Font: Times New Roman
Font: Trebuchet MS
Font: Verdana
Font: Webdings

**Comment by fastfoot** [comment]
On clean UBUNTU SERVER LTS installation there is exception. Is it possible to somehow decouple the library from the operating system configuration. Load the indicated font files explicitly?

Fontconfig error: Cannot load default config file
Unhandled exception. ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/Ren                                 derMVGContent/4504
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:lin                                 e 18
   at ImageMagick.NativeHelper.CheckException(IntPtr exception) in /_/src/Magick.NET/Native/NativeHelper.cs:line 27
   at ImageMagick.DrawingWand.NativeDrawingWand.Render() in /_/src/Magick.NET/Native/Drawables/DrawingWand.cs:line 1236
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables) in /_/src/Magick.NET/MagickImage.cs:line 2564
   at ImageMagick.MagickImage.Draw(IDrawables`1 drawables) in /_/src/Magick.NET/MagickImage.cs:line 2543
   at ImageMagick.Drawables.Draw(IMagickImage`1 image) in /_/src/Magick.NET/Drawables/Drawables.cs:line 46
   at MagickNETFontTest.Program.Main(String[] args) in C:\VS\SPRINT\ITS-3.0\SANDBOX\IronSoftwareDrawing\IronSoftwareDrawing\

**Comment by dlemstra** [comment]
You can also specify the full path to a font file instead.

**Comment by fastfoot** [comment]
Do you mean call 
MagickNET.SetDefaultFontFile(@"/usr/local/share/fonts/OverPass/OverpassMono-Light.ttf"); ?
But what if I need to use more than one font file ? Why .Font(fontFamilyName) doesn't work ?

**Comment by dlemstra** [comment]
I mean that with `.Font("Arial")` you can also specify a path instead `.Font("/usr/local/share/fonts/OverPass/OverpassMono-Light.ttf")`
