### ISSUE TITLE
Drawing Text on .NET7 on MacOS "UnableToReadFont" error

### ISSUE THREAD

**Issue by dan-lego** [dlemstra/Magick.NET#1407]
### Magick.NET version

"Magick.NET.Core" Version="13.1.3" + "Magick.NET-Q16-AnyCPU" Version="13.1.3"

### Environment (Operating system, version and so on)

macOS Ventura 13.4.1 + .NET7

### Description

When I try to draw text on an image I get this error no matter what font I try to use.
I tried setting the `fontconfig` directory, but it had no effect. The only way I could get it to work is to set a font file path in the `Font()` method.

```
ImageMagick.MagickTypeErrorException: UnableToReadFont `' @ error/annotate.c/RenderFreetype/1636
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:line 18
   at ImageMagick.NativeHelper.CheckException(IntPtr exception) in /_/src/Magick.NET/Native/NativeHelper.cs:line 27
   at ImageMagick.DrawingWand.NativeDrawingWand.Render() in /_/src/Magick.NET/Native/Drawables/DrawingWand.cs:line 1218
   at ImageMagick.DrawingWand.Draw(IEnumerable`1 drawables) in /_/src/Magick.NET/Drawables/DrawingWand.cs:line 34
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables) in /_/src/Magick.NET/MagickImage.cs:line 2565
   at ImageMagick.MagickImage.Draw(IDrawables`1 drawables) in /_/src/Magick.NET/MagickImage.cs:line 2545
```

### Steps to Reproduce

https://github.com/dlemstra/Magick.NET/blob/main/docs/Drawing.md

**Comment by dan-lego** [comment]
After reinstalling `fontconfig` and .NET 7 it started working.
