### ISSUE TITLE
Magick.Native-Q8-x64.dll Access Denied (File Locked)

### ISSUE THREAD

**Issue by pdhenrique3** [dlemstra/Magick.NET#1537]
### Magick.NET version

8.2.1

### Environment (Operating system, version and so on)

Windows Server 2016, .NET Framework 4.7.1

### Description

I have two WebAPI Applications on the same Server, different IIS Application Pools, Magick-Q8 8.2.1 AnyCPU. Both of them applies Magick on images contained in the Temp File Path of the Server.

Inside this Path, Magick generates a folder, containing this file Magick.Native-Q8-x64.dll which is used.

![image](https://github.com/dlemstra/Magick.NET/assets/5025294/93482652-d476-43e1-8edb-f4344dc1ee22)
![image](https://github.com/dlemstra/Magick.NET/assets/5025294/7c7605c9-c00c-4c03-bad7-61aac3003981)

When the first application starts, success, but the file Magick.Native-Q8-x64.dll get locked by the application, and the second application's requests gets the error:
```
The type initializer for 'NativeMagickSettings' threw an exception. ---> System.TypeInitializationException: The type initializer for 'X64' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Magick.Native-Q8-x64.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
```

I had to unify both applications under the same Application Pool to make them work, but even if there are no code errors locking the file for any longer than necessary, it happens in some time, and this error could still happen in a much smaller possibility

### Steps to Reproduce

In a Microsoft IIS, Two applications using Magick.NET.Core 8.2.1 and Magick.NET-Q8-AnyCPU 8.2.1, each one in your own AppPool

Open a file in the Server's Tem FilePath, perform image resize and compress, save the file

Do this in both applications

**Comment by dlemstra** [comment]
I would advise you to upgrade to the most recent version. I cannot help you with an older release than the most recent one. 

You can use `MagickNET.`SetNativeLibraryDirectory` to control the location of the folder those files are written. You might be lucky and have that available in your version but I would still advise you to upgrade due to security issues.

**Comment by shanji97** [comment]
Something simmilar is happening on 13.7.0. (upgraded from 13.1.3 when building the daily version of our app. It seems it happens  randomly. Here is the log from the Jenkins build process.
![image](https://github.com/dlemstra/Magick.NET/assets/13587507/270ad61e-bde9-4f98-b4f1-3fac46681cd1)
![image](https://github.com/dlemstra/Magick.NET/assets/13587507/5dd66334-5c92-4862-831a-90e94c0d8023)

**Comment by shanji97** [comment]
🤔 Ok, so I checked the code and put the magick image objects into a using statement. Currently there are no issues related to the locking of the files.

**Comment by dlemstra** [comment]
Thanks for coming back and mentioning this tip for future readers. This is probably going to help someone in the future!

**Comment by shanji97** [comment]
So we encountered a bug where presumably IIS is locking the Image Magick DLLs.
```
URL: our custom
Type: GET
Source: Magick.NET-Q8-AnyCPU
Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'MagickSettings_SetFont' in DLL 'Magick.Native-Q8-x64.dll'.
   at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_SetFont(IntPtr Instance, IntPtr value)
   at ImageMagick.MagickSettings.NativeMagickSettings.SetFont(String value)
   at ImageMagick.MagickSettings.CreateNativeInstance(IMagickSettings`1 instance)
   at ImageMagick.MagickImage.NativeMagickImage..ctor(IMagickSettings`1 settings)
   at ImageMagick.MagickImage..ctor()
   at ImageMagick.MagickImage..ctor(Stream stream)
   at Pages_Vlozisce_Attachment.GeneralScaleImage(Byte[] attachmentData, Int32 rotation, Int32 page)
   at Pages_Vlozisce_Attachment.ScaleImage(Byte[] attachmentData, Int32 rotation, Int32 page, MimeType mimeType)
   at Pages_Vlozisce_Attachment.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at Marg.BusinessConnect.Gui.BasePage.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```
   I checked the DLL with Dependency Walker x64 and every DLL I scanned containted the aforementioned entry point. Since I had another IM related feature request (the support of HEIC and HEIF files), I noticed, that I had trouble to remove the Magick.Native-Q8-x64.dll with the command `nant.cmd clean`. What worked was to recycle the IIS Application Pool and then the deletion worked perfectly. I the manually changed the DLL on our test server (of course I recycled the Application Pool first) and then the upgrade/replacement of the DLL worked smoothly and no errors are being thrown. Is there any way to track these kind of DLL locks on a low level?

**Comment by wsion** [comment]
@pdhenrique3 I am using Magick.Net 7.17.0.0 in my application, and met exactly the same issue some days ago. Not sure how the other version does, by reading the source code of the version I'm using, I see **SetNativeLibraryDirectory()** not really set the directory for extracting and place the native libary. In fact, the folder in windows temp folder for placing the native libary named **CacheDirectory**.  Finally I resolved the issue by manually set the CacheDirectory to other places in during starting my application. Below code might help someone who met similar issue. I just put the code snippet in my Application_Start() method of Global.asax.cs..

![image](https://github.com/user-attachments/assets/d33534ca-c275-4f57-82f3-c8608e8508da)

**Comment by shanji97** [comment]
> @pdhenrique3 I am using Magick.Net 7.17.0.0 in my application, and met exactly the same issue some days ago. Not sure how the other version does, by reading the source code of the version I'm using, I see **SetNativeLibraryDirectory()** not really set the directory for extracting and placing the native libary. In fact, the folder in windows temp folder for placing the native libary named **CacheDirectory**. Finally I resolved the issue by manually setting the CacheDirectory to other place during starting my application. Below code might help someone who met similar issue. I just put the code snippet in my Application_Start() method of Global.asax.cs..
> 
> ![image](https://private-user-images.githubusercontent.com/23180777/356795897-d33534ca-c275-4f57-82f3-c8608e8508da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTE0MjQsIm5iZiI6MTcyNTk1MTEyNCwicGF0aCI6Ii8yMzE4MDc3Ny8zNTY3OTU4OTctZDMzNTM0Y2EtYzI3NS00ZjU3LTgyZjMtYzg2MDhlODUwOGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA2NTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZGY3OTY0YWYxN2EwMmE2YjQwYWM4ZTQ2NGExNDJiNzdlZmZmYWVhYjU3M2Y2NzQyMjZhNWU1ODhhYzRmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QgUb6L36Ga92N_Wvse76mQt8PPGuZhUS4K06u66ZReE)

Is this somehow applicable when using nuget packages Magick.NET.Core and AnyCPU.Q16-HDRI? The version is 13.9.1. The error is  MagickAnyCPU does not exist in the namespace ImageMagick. (CS0234 error)

**Comment by dlemstra** [comment]
The `SetNativeLibraryDirectory` method has moved to the MagickNET class.
