### ISSUE TITLE
ImageMagick.MagickDelegateErrorException

### ISSUE THREAD

**Issue by julian-dimitroff** [dlemstra/Magick.NET#1561]
### Magick.NET version

Magick.NET-Q8-AnyCPU 13.4.1

### Environment (Operating system, version and so on)

Linux

### Description

Hello,
We have an exception thrown in our production environment when we are processing .pdf files and convert them to images in parallel batches by 10. We are trying to reproduce the problem on local environment but failed, so we are hoping that with the exception that we have, to help us understand what exactly causes the problem.  

### Steps to Reproduce

the way we implemented the .pdf to image conversion is like this:
```cs
    var input = new Dictionary<string, int>()
    {
        //{ "Multiple_Pages.pdf", 1 },
        //{ "original0000.pdf", 2 },
        { "huge.pdf", 3 },
    };

    var storageFolder = "output";

    await input.ForEachAsync(async i =>
    {
        int totalPages = 0;
        using (var document = new Document(i.Key))
        {
            totalPages = document.Pages.Count;
        }

        var magickSettings = new MagickReadSettings();
        magickSettings.Density = new Density(300);

        var storageFileNames = new ConcurrentBag<string>();

        var batchSize = 10;

        for (int batchStartIndex = 0; batchStartIndex < totalPages; batchStartIndex += batchSize)
        {
            var tasks = new ConcurrentBag<Task>();
            var batchEndIndex = Math.Min(batchStartIndex + batchSize, totalPages);
            for (int pageIndex = batchStartIndex; pageIndex < batchEndIndex; pageIndex++)
            {
                int currentPageIndex = pageIndex;
                tasks.Add(Task.Run(async () =>
                {
                    using (var document = new Document(i.Key))
                    {
                        var page = document.Pages[currentPageIndex + 1];

                        using (var memoryStream = new MemoryStream())
                        {
                            using (var newDocument = new Document())
                            {
                                newDocument.Pages.Add(page);

                                newDocument.Save(memoryStream);
                                memoryStream.Position = 0;

                                using (var magickImage = new MagickImage(memoryStream, magickSettings))
                                {
                                    magickImage.Format = MagickFormat.Png;

                                    var storageFileName = $"{fileSystem.Path.GetFileName(i.Key)}_image{currentPageIndex:D4}.png";
                                    var storagePath = $"{storageFolder}/{storageFileName}";

                                    // We create a separate image which is the background  try to set its background color of the original image and put the image on top.
                                    using (var background = new MagickImage(magickImage.BackgroundColor ?? MagickColors.White, magickImage.Width, magickImage.Height))
                                    {
                                        magickImage.BackgroundColor = new MagickColor(MagickColors.Transparent); // Try to remove the background from the original image for size reasons
                                        background.Format = MagickFormat.Png;
                                        background.Composite(magickImage, CompositeOperator.Over);

                                        using (var stream = new MemoryStream())
                                        {
                                            await background.WriteAsync(stream);

                                            stream.Position = 0;
                                            using (var fs = new FileStream(storagePath, FileMode.OpenOrCreate))
                                            {
                                                stream.CopyTo(fs);
                                            }

                                            storageFileNames.Add(storageFileName);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }));
            }

            await Task.WhenAll(tasks);
        }
    });
}
```
The line that the exception is thrown is `using (var magickImage = new MagickImage(memoryStream, magickSettings))` this one.
Basically we have a .pdf document and we loop through its pages in batches by 10 in parallel. The error it gives is as follows:
```
ImageMagick.MagickDelegateErrorException
FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r300x300' -dPrinted=false -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-ax-urC84Hqy1qih3k12P_T7Kbp5X0mRe%d' '-f/tmp/magick-w5llH-WDz_hAGFB9n7NKtCIq2xpUb2Zv' '-f/tmp/magick-DZK8Pir9YMSj0jrdAGLSeWzPYun7fioV'' (-1) @ error/delegate.c/ExternalDelegateCommand/522

ImageMagick.MagickDelegateErrorException: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r300x300' -dPrinted=false -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-ax-urC84Hqy1qih3k12P_T7Kbp5X0mRe%d' '-f/tmp/magick-w5llH-WDz_hAGFB9n7NKtCIq2xpUb2Zv' '-f/tmp/magick-DZK8Pir9YMSj0jrdAGLSeWzPYun7fioV'' (-1) @ error/delegate.c/ExternalDelegateCommand/522
   at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(IMagickSettings`1 settings, Byte[] data, Int32 offset, Int32 length) in /_/src/Magick.NET/Native/MagickImage.cs:line 6923
   at ImageMagick.MagickImage.Read(Stream stream, IMagickReadSettings`1 readSettings, Boolean ping) in /_/src/Magick.NET/MagickImage.cs:line 7581
   at IM.ImageRendering.Services.RenderingService.<>c__DisplayClass7_2.<<ExecuteInParallelAsync>b__2>d.MoveNext() in /app/IM.ImageRendering/Services/RenderingService.cs:line 160
--- End of stack trace from previous location ---
   at IM.ImageRendering.Services.RenderingService.<>c__DisplayClass7_0.<<ExecuteInParallelAsync>b__0>d.MoveNext() in /app/IM.ImageRendering/Services/RenderingService.cs:line 192
--- End of stack trace from previous location ---
   at IM.ImageRendering.Extensions.EnumerableExtensions.ForEachAsync[T](IEnumerable`1 enumerable, Func`2 action) in /app/IM.ImageRendering/Extensions/EnumerableExtensions.cs:line 14
```

As I said we were not able to recreate the exception, but this code was working on our production environment for more than 6 months without any issues. We are hoping that based on the exception, you can suggest what might the problem be.

Out humble assumptions are that it is somehow a concurrency issue, or because we updated the .NET version from .NET6  to .NET8 and that might cause some issues, but sadly we could not find and breaking changes that we can relate to that problem.

Best regards,

**Comment by dlemstra** [comment]
Do you have Ghostscript installed in your Linux environment?

**Comment by julian-dimitroff** [comment]
> Do you have Ghostscript installed in your Linux environment?

Yes, version 10.0

**Comment by dlemstra** [comment]
I just noticed that you are not using the most recent version of Magick.NET and you mentioned a version that does not exist? I would advise you to always use the most recent version.

It seems to happen when ImageMagick executes a command on the command line. It would probably be wise to see if you can reproduce this on the command line with Ghostscript and contact their support when you have created something they can use to reproduce it.I suspect this is some kind of parallel issue inside Ghostscript but it also looks like you can add some improvements to the code that might make it easier to reproduce the issue:

You don't need to create that separate document. You can specify the page of the document with the following code:

```C#
var settings = new MagickReadSettings
{
    FrameIndex = 0, // First page
    FrameCount = 1, // Number of pages
};
```
And you also don't need that `stream` when you write the `background`. You can directly write to the `storagePath`.

**Comment by julian-dimitroff** [comment]
Hello, thank you for your quick answer,
```
var settings = new MagickReadSettings
{
    FrameIndex = 0, // First page
    FrameCount = 1, // Number of pages
};
```
Does this mean that all pages will go to one big image? Because our goal is to have separate image for every page?

**Comment by dlemstra** [comment]
With `FrameIndex` you specify the starting page that should be read and `FrameCount` the number of pages. So in this case you are reading the "first 1 pages" of the pdf file.

**Comment by julian-dimitroff** [comment]
Yes, thank you, I'll close this issue.

Regards
