### ISSUE TITLE
Azure function System.DllNotFoundException on linux

### ISSUE THREAD

**Issue by PetterKnudsen98** [dlemstra/Magick.NET#1567]
### Magick.NET version

Magick.NET-Q16-x64

### Environment (Operating system, version and so on)

Linux - Ubuntu 22.04.4

### Description

Running .net 6 on an azure function v4 I get the following error message

`System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMagick.Native-Q16-x64.dll: cannot open shared object file: No such file or directory
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 65
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 21
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 315`

when executing the following code:
`using var image = new MagickImage(imageStream);`

My .csproj looks like this:

```

 <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <MagickCopyNativeLinux>true</MagickCopyNativeLinux>
    </PropertyGroup>
    
    <ItemGroup>
        ...
        <PackageReference Include="Magick.NET-Q16-x64" Version="13.6.0" />
        ...
    </ItemGroup>

```

I have seen other suggest that `<MagickCopyNativeLinux>true</MagickCopyNativeLinux>` fixes the issue, but it doesnt seem to work for me. Is this an azure function issue, or am I just doing something wrong? 

It works fine on windows, and I'm not very experience with linux.

### Steps to Reproduce

1. Run on a linux machine, only tested with ubuntu and in azure (it doesnt specify linux version)
2. Run azure function
3. Execute code that uses the library

**Comment by dlemstra** [comment]
How did you test it on Linux? Do you see the `Magick.Native-Q16-x64.dll` file in your bin directory?

The `MagickCopyNativeLinux` option does not work for `net6.0` because it should be necessary there.

**Comment by PetterKnudsen98** [comment]
Its not in the bin directory IIRC. Tried to use SkiaSharp as well, same issue there. Tested with an empty project, worked fine. As soon as it was an azure function it failed. To resolve it with SkiaSharp we added

```
<PropertyGroup>    
  <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
</PropertyGroup>

<Target Name="CopySkiaLib" AfterTargets="Build">
  <ItemGroup>
    <SkiaSharpLibraryFiles Include="$(TargetDir)/libSkiaSharp.so" />
  </ItemGroup>
  <Copy SourceFiles="@(SkiaSharpLibraryFiles)" DestinationFolder="$(TargetDir)/bin" />
</Target>
```

I have been meaning to check if a similar work around will work with magick, but have been a bit busy.

**Comment by dlemstra** [comment]
I wonder if I could also add something like the `@(SkiaSharpLibraryFiles)` the the targets file of this project to make it convenient for you.

**Comment by ignars3** [comment]
I have the same issue. Everything works locally, but not after deploying my changes with Azure.
My OS is Alpine 3.16-24.
This is my csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-HDRI-AnyCPU" Version="13.5.0" />
  </ItemGroup>
  <PropertyGroup>
    <MagickCopyNativeLinux>true</MagickCopyNativeLinux>
  </PropertyGroup>
</Project>
```
And here is the error I get: 
`System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-HDRI-arm64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libMagick.Native-Q16-HDRI-arm64.dll: No such file or directory at ImageMagick.Environment.NativeMethods.ARM64.Environment_Initialize() at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 59 at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 18 at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 321 --- End of inner exception stack trace ---`

I verified that the output folder contains these files:
Magick.NET-Q16-HDRI-AnyCPU.dll
Magick.NET.Core.dll
Magick.Native-Q16-HDRI-arm64.dll.so
Magick.Native-Q16-HDRI-x64.dll.so

I also tried to add the 'lib' prefix to the Native libraries by adding this in my Dockerfile. But I still get the same error (I verified that renaming was successful). 

```
mv '/app/Magick.Native-Q16-HDRI-arm64.dll.so' '/app/libMagick.Native-Q16-HDRI-arm64.dll.so'
mv '/app/Magick.Native-Q16-HDRI-x64.dll.so' '/app/libMagick.Native-Q16-HDRI-x64.dll.so'
```

Does it mean that I am missing some dependency?

**Comment by PetterKnudsen98** [comment]
Ok, so I got around to test it.

The following worked for me locally, I have no tried it in azure, but I'm assuming it works since it did for SkiaSharp, so it should for this as well. What I did was add `<RuntimeIdentifier>linux-x64</RuntimeIdentifier>` as well as the target "CopyMagick".

This should copy the .so file into the bin folder so that the code finds it. 
RuntimeIdentifier can be changed to <RuntimeIdentifiers>linux-x64;win-x64 (etc) </RuntimeIdentifiers> if multiple runtimes are used, E.G windows in local dev but linux in cloud.

```
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier> \
    </PropertyGroup>
    <Target Name="CopyMagick" AfterTargets="Build">
        <ItemGroup>
            <MagickLibraryFiles Include="$(TargetDir)/Magick.Native-Q16-x64.dll.so" />
        </ItemGroup>
        <Copy SourceFiles="@(MagickLibraryFiles)" DestinationFolder="$(TargetDir)/bin" />
    </Target>
```

**Comment by dlemstra** [comment]
I just created an function app to test if I can reproduce this. And I am unable to reproduce your issue. Would it be possible to share a trimmed down project that I can use to reproduce your issue? I did this in my test function: `response.WriteString(MagickNET.Version);`.

**Comment by PetterKnudsen98** [comment]
[This](https://github.com/PetterKnudsen98/MagickAzFunctionTest) repo should reproduce it, at least it does for me.

![image](https://github.com/dlemstra/Magick.NET/assets/69466741/2c99f1fc-1e26-42ce-b047-0763bc1023ee)

**Comment by dlemstra** [comment]
Does it only fail in a unit test or also when running on Azure?

**Comment by PetterKnudsen98** [comment]
It fails locally and in azure, I only named the function "Test", its not an actual unit test (my bad, bad naming).

**Comment by dlemstra** [comment]
It works on my machine and in Azure? 
![afbeelding](https://github.com/dlemstra/Magick.NET/assets/10426229/7ed0854f-ad65-4da3-aef0-b6853f5c90b1)
Maybe this is related to your IDE, I am using Visual Studio.

**Comment by dlemstra** [comment]
I am on Windows and publishing the application through Visual Studio on Azure. I suspect that Rider packages it differently. Not sure when I have time for this but I will setup VM and use rider there and check what they do. What you could do is go to your nuget cache and copy the .targets file from the netstandard20 folder to netstandard21 folder. (you need to create it) And then set the copy linux variable again. Does that work?

**Comment by dlemstra** [comment]
Did my "patch" work for you @PetterKnudsen98?
