### ISSUE TITLE
Libraarty running under Avalonia XPF.

### ISSUE THREAD

**Issue by mauisoftware** [dlemstra/Magick.NET#1742]
### Magick.NET version

14.0.0

### Environment (Operating system, version and so on)

Avalonia XPF

### Description

The following line crashes under Avalonia XPF Indie which requires Avalonia nightly builds (currently 11.3.999-cibuild0052834-alpha)...

var image = new MagickImage(imagePath);

System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'Environment_Initialize' in DLL 'Magick.Native-Q8-x64.dll'.
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Generated/Magick.NET.SourceGenerator/ImageMagick.SourceGenerator.NativeInteropGenerator/Environment.g.cs:line 62
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 21
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Generated/Magick.NET.SourceGenerator/ImageMagick.SourceGenerator.NativeInteropGenerator/MagickSettings.g.cs:line 299
   --- End of inner exception stack trace ---
   at ImageMagick.MagickSettings.NativeMagickSettings.Create() in /_/src/Magick.NET/Generated/Magick.NET.SourceGenerator/ImageMagick.SourceGenerator.NativeInteropGenerator/MagickSettings.g.cs:line 333
   at ImageMagick.MagickSettings..ctor() in /_/src/Magick.NET/Settings/MagickSettings.cs:line 33
   at ImageMagick.MagickImage..ctor() in /_/src/Magick.NET/MagickImage.cs:line 43
   at ImageMagick.MagickImage..ctor(String fileName) in /_/src/Magick.NET/MagickImage.cs:line 200

### Steps to Reproduce

Call var image = new MagickImage(imagePath); under the mentioned conditions.

**Comment by kekekeks** [comment]
The issue is not related to Magick.NET. You've enabled the [XPF Win32 API shim](https://docs.avaloniaui.net/xpf/third-party-libraries) which by default installs a catch-all redirect for P/Invoke's. You need to manually whitelist ImageMagick as described in the linked doc, e. g. 
```cs
AvaloniaUI.Xpf.WinApiShim.WinApiShimSetup.
  .AutoEnable(asm =>
  {
    var name = asm.GetName().Name.ToLowerInvariant();
    if (name is "magick.net" or "magick.net.core")
      return true;
    return false;
  });
  ```

**Comment by mauisoftware** [comment]
Thanks, I missed that in the Avalonia docs.  Awesome product!
