### ISSUE TITLE
System.AccessViolationException applying BrightnessContrast

### ISSUE THREAD

**Issue by Brubning** [dlemstra/Magick.NET#199]
I have used Magick.NET in a desktop application that deals with large numbers of images in a listview. On one machine I am getting a System.AccessViolationException whenever an image is corrected by applying BrightnessContrast.

The application stops with a "not responding" error.

I'm running Q16-AnyCPU v7.4.3. On all other machines it's running OK, any ideas on whether I may have a missing pre-requisite? I didn't think the Visual C++ Redist was a requirement any more, although versions up to 2014 are installed (x64 and x86).

Thanks

Exception Details from Event Viewer:
Application: Vancols.Wpf.Production.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at ImageMagick.MagickImage+NativeMethods+X64.MagickImage_BrightnessContrast(IntPtr, Double, Double, UIntPtr, IntPtr ByRef)
   at ImageMagick.MagickImage+NativeMagickImage.BrightnessContrast(Double, Double, ImageMagick.Channels)
   at ImageMagick.MagickImage.BrightnessContrast(ImageMagick.Percentage, ImageMagick.Percentage, ImageMagick.Channels)
   at Vancols.Core.Imaging.ImageManipulation.ColourCorrectImage(ImageMagick.MagickImage, Vancols.Core.Imaging.ImageCorrection)
   at Vancols.Core.Imaging.ImageManipulation.ColourCorrectImage(Byte[], Vancols.Core.Imaging.ImageCorrection)
   at Vancols.Wpf.Production.Converters.ImageCorrectionsConverter.Convert(System.Object, System.Type, System.Object, System.Globalization.CultureInfo)
   at System.Windows.Data.BindingExpression.TransferValue(System.Object, Boolean)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean, Boolean, Boolean)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32, System.ComponentModel.ICollectionView, System.Object, Boolean)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(System.Object, System.String)
   at System.Windows.WeakEventManager+ListenerList`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].DeliverEvent(System.Object, System.EventArgs, System.Type)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(System.Object, System.ComponentModel.PropertyChangedEventArgs)
   at Vancols.Wpf.Production.UI.BaseViewModel.RaisePropertyChanged(System.String)
   at Vancols.Wpf.Production.UI.BaseViewModel.Set[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef, System.__Canon, System.String)
   at Vancols.Wpf.Production.UI.PrintJob.ImageListViewModel.set_SelectedPrintJobImage(Vancols.Wpf.Production.UI.PrintJob.PrintJobImageViewModel)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.RuntimePropertyInfo.SetValue(System.Object, System.Object, System.Object[])
   at MS.Internal.Data.PropertyPathWorker.SetValue(System.Object, System.Object)
   at System.Windows.Data.BindingExpression.UpdateSource(System.Object)
   at System.Windows.Data.BindingExpressionBase.UpdateValue()
   at System.Windows.Data.BindingExpressionBase.ProcessDirty()
   at System.Windows.Data.BindingExpressionBase.Dirty()
   at System.Windows.Data.BindingExpressionBase.SetValue(System.Windows.DependencyObject, System.Windows.DependencyProperty, System.Object)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetCurrentValueInternal(System.Windows.DependencyProperty, System.Object)
   at System.Windows.Controls.Primitives.Selector.UpdatePublicSelectionProperties()
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector+SelectionChanger.SelectJustThisItem(ItemInfo, Boolean)
   at System.Windows.Controls.ListBox.MakeSingleSelection(System.Windows.Controls.ListBoxItem)
   at System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(System.Windows.Input.MouseButton)
   at System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Window.ShowDialog()
   at Vancols.Wpf.Production.App+<OnStartup>d__1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Vancols.Wpf.Production.App.Main()

**Comment by dlemstra** [comment]
Do you have an NVIDIA video card on the machine that has this issue?

**Comment by Brubning** [comment]
Yes, apparently he has a Quadro K2000.

On 17 Apr 2018 12:48, "Dirk Lemstra" <notifications@github.com> wrote:

Do you have an NVIDIA video card on the machine that has this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dlemstra/Magick.NET/issues/199#issuecomment-381962457>,
or mute the thread

**Comment by dlemstra** [comment]
We have had several OpenCL issue with NVIDIA and I suspect it is happening here again. I will make a change to ImageMagick so we will no longer enable OpenCL by default for NVIDIA devices. You can still use it but it won't be enabled by default. The quick win for now is to do `OpenCL.IsEnabled=false` but I will try to add this patch later tonight and publish a new release.

**Comment by Brubning** [comment]
Awesome. One of the guys on site has just told me that they've changed the drivers to a different version and it is now OK, also. I'll find out what version number they are running (not that it particularly matters, I guess)

**Comment by dlemstra** [comment]
I just publish 7.4.4.0 that will have OpenCL disable when an NVIDIA devices is detected.

**Comment by Brubning** [comment]
Thanks. I'll update my stuff later today and publish to the users.
