### ISSUE TITLE
ImageMagick.MagickCoderErrorException: WriteBlob Failed

### ISSUE THREAD

**Issue by jcmag** [dlemstra/Magick.NET#233]
Hi,

Sometimes when my app calls MagickImage.Write, I get this error:

ImageMagick.MagickCoderErrorException: WriteBlob Failed `c:\temp\myimage.png' @ error/png.c/MagickPNGErrorHandler/1666
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.MagickImage.NativeMagickImage.WriteFile(MagickSettings settings)
   at ImageMagick.MagickImage.Write(FileInfo file)
   at TwitterRss.MonitorRss.ProcessRequest(HttpContext context) 

Do you have an idea about what could be the problem?

**Comment by dlemstra** [comment]
Is it possible to create a small sample program that can be used to reproduce the issue? And which version of Magick.NET are you using?
