### ISSUE TITLE
System.AccessViolationException applying ColorSpace

### ISSUE THREAD

**Issue by programatix** [dlemstra/Magick.NET#336]
### Description
I'm using Magick.NET with AForge.Video.DirectShow in its NewFrame event (http://www.aforgenet.com/framework/docs/html/0592d628-6d09-b601-1b72-d04f55fc748f.htm). It triggered the exception when I tried to change the ColorSpace to gray. It has no issue with Rotate, Crop, ContracstStretch and Normalize.

### Steps to Reproduce
The following is the code snippet
```
        private void CameraNewFrame(object sender, NewFrameEventArgs eventArgs)
        {
            var newFrame = eventArgs.Frame.Clone() as System.Drawing.Bitmap;

            Dispatcher.Invoke(() =>
            {
                ImageMagick.IMagickImage image = new ImageMagick.MagickImage(newFrame);
                image.ColorSpace = ImageMagick.ColorSpace.Gray; // exception occurs
            });
        }
```
The following is the exception
```
"System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImageMagick.MagickImage.NativeMethods.X86.MagickImage_ColorSpace_Set(IntPtr instance, UIntPtr value, IntPtr& exception)
   at ImageMagick.MagickImage.NativeMagickImage.set_ColorSpace(ColorSpace value)
   at ImageMagick.MagickImage.set_ColorSpace(ColorSpace value)
   at xxx.MyWebCam.<>c__DisplayClass43_0.<CameraNewFrame>b__1() in MyWebCam.xaml.cs:line xxx
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at xxx.Main()"
```

### System Configuration
- Magick.NET version: Magick.NET-Q8-AnyCPU 7.8.0
- Environment (Operating system, version and so on):
   - Windows 10.0.17763.55
   - .NetFramework 4.7.2
- Additional information:

**Comment by dlemstra** [comment]
Is it possible to create a small application that is not using AForge.Video.DirectShow? I have no idea what could cause this so I would like to reproduce the issue in a small/simple application.

p.s You are missing `using` statements so you are probably also leaking memory.

**Comment by programatix** [comment]
From the other thread (https://github.com/dlemstra/Magick.NET/issues/199), I tried setting ```ImageMagick.OpenCL.IsEnabled = false``` and it doesn't crash anymore. I'm not using NVIDIA GPU though. It's Intel HD Graphics 630. Would I be losing anything from setting OpenCL to false?

I'll try to reproduce this issue without AForge, but I doubt I can manage, since it seems to me like the crash happened inside an event (where the handler is in the main EXE) called by a different DLL?

**Comment by programatix** [comment]
It turned out that the problem will show itself with simple snippet below. I placed the code snippet in the start up function.
```
var a = new ImageMagick.MagickImage("image.jpg");
a.ColorSpace = ImageMagick.ColorSpace.Gray;
```
with the following exception,
```
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ImageMagick.MagickImage.NativeMethods.X86.MagickImage_ColorSpace_Set(IntPtr instance, UIntPtr value, IntPtr& exception)
   at ImageMagick.MagickImage.NativeMagickImage.set_ColorSpace(ColorSpace value)
   at ImageMagick.MagickImage.set_ColorSpace(ColorSpace value)
   at ....App.Application_Startup(Object sender, StartupEventArgs e) in ...
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ....App.Main()
```

Besides setting the ```ColorSpace```, calling the ```Resize()``` method will also caused similar exception. As mentioned before, disabling OpenCL seems to workaround the issue. Please note that this issue originally does not exists on my development PC until Windows 10 was updated to the latest ```Feature update to Windows 10, version 1809``` and ```Feature update to Windows 10 (business editions), version 1809```. The ```Intel(R) HD Graphics 630``` driver remains the same, which is version ```23.20.16.4974 (28/2/2018)```.

**Comment by dlemstra** [comment]
Setting just ColorSpace cannot be the issue because there is no OpenCL being used at that point. So I need a better/smaller example to make it possible to reproduce your issue. What happens when you take the Dispatcher.Invoke out of the equation?

**Comment by programatix** [comment]
As mentioned in the latest code snippet, I placed the code in the startup function for WPF application and the exception was triggered. I tried it in another machine with different Intel GPU and no exception. Lastly, I updated the Intel GPU on my pc and it now doesn't cause any exception anymore.

**Comment by dlemstra** [comment]
Most likely a drivers issue then.
