### ISSUE TITLE
MagickColors.Transparent Causes Error in Docker Container

### ISSUE THREAD

**Issue by ginluk** [dlemstra/Magick.NET#464]
### System Configuration
I'm running the code in a docker linux container.

- Magick.NET version: Magick.NET-Q16-AnyCPU (7.13.1)
- Environment (Operating system, version and so on): 
     **Microsoft.AspNetCore.App (2.2.0)
     **Docker linux container
     **Transparent background works in IIS environment

### Question
Hello!  Great library that does exactly what I want.  I am converting an SVG string into a PNG with a transparent background, then saving that image to a Bitmap.  Everything works great in a Windows environment on IIS, however when I push to a linux container, I get a 'System.ArgumentException: Parameter is not valid.' error.  If I simply comment out the code for the transparent background color, it will run in the container.  Have you run into issues trying to use transparency in a linux container?  Thank you!

[svg2PngMethod.txt](https://github.com/dlemstra/Magick.NET/files/3292385/svg2PngMethod.txt)

**Comment by ginluk** [comment]
`public static Image Svg2Png(string s, int sizex = 100, int sizey = 100)
        {
            byte[] bytes = Encoding.UTF8.GetBytes(s);
            MemoryStream stream = new MemoryStream(bytes);

            MagickReadSettings settings = new MagickReadSettings();
            settings.Density = new Density(300);
            settings.BackgroundColor = MagickColors.Transparent; //THIS LINE SEEMS TO CAUSE THE ERROR
            byte[] imgBytes;
            using (MagickImage image = new MagickImage())
            {
                image.Read(stream, settings);
               
            //    Sets the output format to png
                image.Format = MagickFormat.Png24;

            //    Create byte array that contains a jpeg file
                imgBytes = image.ToByteArray();
            }
            Bitmap image2 = new Bitmap(Tools.byteArrayToImage(imgBytes), sizex, sizey);

            //SaveImage(image2, @"C:\Temp\NatTest.png");

            return image2;
        }`

**Comment by dlemstra** [comment]
You should not add ImageMagick to the container. You don't need it. Magick.NET comes bundled with that library. And under Linux you can at this point in time not use the `-AnyCPU` version. You will need to switch to the `-x64` version for now. And last but not least you cannot use the `Bitmap` class on Linux and I don't even understand why you are using it.

**Comment by ginluk** [comment]
Thanks so much for your quick response!  I installed the Q16-x64 version and removed the line to add ImageMagick to the container.  However, I'm still having the same issue.  If I comment out the line

`settings.BackgroundColor = MagickColors.Transparent;`

then my code works and I can generate and image.  If that line is not commented, I receive an error.  Interestingly, if I run the code in IIS and not in the container, I it still works with the transparent code in place.  Any ideas why this might be happening?  Is there a better alternative to generating a png with a transparent background from an SVG (than settings.BackgroundColor)?

**Comment by ginluk** [comment]
`# the first thing we specify in a Dockerfile is the base image
FROM keymetrics/pm2:latest-alpine

RUN yarn global add pm2@latest

# Install image preview generator tools
#RUN apk add --no-cache file
#RUN apk --update add imagemagick

# Install fonts
RUN apk --no-cache add msttcorefonts-installer fontconfig && \
 update-ms-fonts && \
 fc-cache -f

FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

#######################################################
# Add dependencies for Gdip in the runtime application. System.Drawing. 
#######################################################

RUN ln -s /lib/x86_64-linux-gnu/libdl-2.24.so /lib/x86_64-linux-gnu/libdl.so
RUN apt-get update && apt-get -y install inkscape

# install System.Drawing native dependencies
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
   		libgdiplus \
         libc6-dev \
         libx11-dev \
     && rm -rf /var/lib/apt/lists/*


############################### END of Gdip dependencies

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["...", "..."]
RUN dotnet restore "..."
COPY . .

WORKDIR "..."
RUN dotnet build "..." -c Release -o /app

FROM build AS publish
RUN dotnet publish "..." -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "..."]`

Here's the docker file for reference.

**Comment by kendallmark3** [comment]
Yes I get the same issue- I tried image2.MakeTransparent(); after the bitmap was created no error but the quality wasn't quite right? still searching for solution

**Comment by kendallmark3** [comment]
We tried a hack but not not so good-we remembered how to get the MakeTransparent to work - we have to make the svg background pink (or some other wacky color).  Then use that hex code in MakeTransparent.
It should work, but the result will be a really fuzzy image.

**Comment by kendallmark3** [comment]
this works ImageMagick.MagickColor.FromRgb(255, 255, 255) 
but no alpha for transparency
but not ImageMagick.MagickColor.FromRgba(255, 255, 255,0)

**Comment by kendallmark3** [comment]
New Stack Trace
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLNK1PKVG6SC", Request id "0HLNK1PKVG6SC:00000002": An unhandled exception was thrown by the application.
System.Exception: Error: Parameter is not valid.     at System.Drawing.Image.CreateFromHandle(IntPtr handle)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at bam2export.ApplicationCore.Tools.Svg2Png(String s, Int32 sizex, Int32 sizey) in /src/bam2export.ApplicationCore/Tools.cs:line 259
   at bam2export.ApplicationCore.AddPointsRepository.AddPoints(Image img, PointsEntity points, Double lat, Double lng, Double zoom, Int32 sizex, Int32 sizey) in /src/bam2export.ApplicationCore/AddPointsRepository.cs:line 56
   at bam2export.ApplicationCore.ExportRepository.getImage(MapObjectEntity mo) in /src/bam2export.ApplicationCore/ExportRepository.cs:line 63
   at bam2export.Web.Controllers.ExportController.Post(MapObjectEntity mapObj) in /src/bam2export.Web/Controllers/ExportController.cs:line 113
   at bam2export.Web.Controllers.ExportController.Post(MapObjectEntity mapObj) in /src/bam2export.Web/Controllers/ExportController.cs:line 122
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by dlemstra** [comment]
This is not an error inside the Magick.NET library:
```
System.Exception: Error: Parameter is not valid. at System.Drawing.Image.CreateFromHandle(IntPtr handle)
at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
```

So I cannot help you with this.

**Comment by kendallmark3** [comment]
If we change the image to  image.Format = MagickFormat.Jpeg; Jpeg- we can set the alpha 
 image.BackgroundColor = MagickColor.FromRgba(0, 0, 0, 0);
turns background to black from  white- we have tried lots of combinations and transparencies- but still short of good.
