### ISSUE TITLE
Was there a change to override custom Policy.xml content?

### ISSUE THREAD

**Issue by vhdevito** [dlemstra/Magick.NET#496]
### System Configuration

- Magick.NET version: 7.14.1
- Environment (Operating system, version and so on): Windows 10 and Windows Server 2016

### Question
I had been allowing SVG files using Magick.NET 7.12.0 and temporary disabled them using a custom policy file with:
```csharp
ConfigurationFiles config = ConfigurationFiles.Default;
config.Policy.Data = @"<policy text here>";
MagickNET.Initalize(config);
```
Now I want to reenable them, however we're seeing this error when trying to open an image after removing the SVG line from the policy in Magick.NET 7.14.0:
```
attempt to perform an operation not allowed by the security policy 'SVG' @ error/constitute.c/IsCoderAuthorized/408
StackTrace:    at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImageCollection.AddImages(Stream stream, MagickReadSettings readSettings, Boolean ping)
```

Is there another way to enable coder rights or is there something overriding this internally?

**Comment by dlemstra** [comment]
Is it possible to create a small repository that demonstrates this issue?

**Comment by vhdevito** [comment]
I'm not sure, because I can't get the issue to repro locally in Windows 10.  It reproes relatively consistently in our Windows Server 2016 build machines.  I can provide one that replicates how I'm using the libraries, if that helps.

**Comment by dlemstra** [comment]
Are you aware that this is a global setting? Maybe multiple threads are changing things at the same time?

**Comment by vhdevito** [comment]
This was my first thought, but the code only has 2 separate uses of Magick.NET and both preface with the same setup method that's shown above.  Furthermore, I haven't added or changed the code that uses Magick.NET since it was working (except to disable then reenable SVG and update Magic.NET package version).

**Comment by dlemstra** [comment]
Can you confirm that you are not running into the following issue?

- Thread1 enables SVG reading.
- Thread2 enables SVG reading.
- Thread1 reads the SVG image.
- Thread1 disables SVG reading.
- Thread2 reads the SVG image and fails.

**Comment by vhdevito** [comment]
How would thread 1 disable svg reading? Would it have to actively change
the policy again or is there some cleanup work that resets those settings?
We don't actively touch the policy settings after enabling svg.

**Comment by dlemstra** [comment]
I am sorry for confusing you. You are correct that it is not possible to enable a coder after it has been disabled and ImageMagick has been initalized.

But now I don't understand what you are asking/reporting.

**Comment by dlemstra** [comment]
With `<policy domain=""coder"" rights=""none"" pattern=""SVG"" />` will disable the SVG code because the rights are changed to `none`. If you remove that line form your policy the SVG coder will be enabled.

**Comment by dlemstra** [comment]
Would it be possible to create a small example in a repository that demonstrates this issue?
