### ISSUE TITLE
The type initializer for 'NativeMagickSettings' threw an exception in linux docker 

### ISSUE THREAD

**Issue by NagaRajeshK** [dlemstra/Magick.NET#556]
I am facing the following issue. Please do find attached docker file. I am not able to make ImageMagick work in my docker.Works fine in my windows.I have added package reference in my .net core project like below.
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="7.15.0"/>
Could you please help me?

[Dockerfile.txt](https://github.com/dlemstra/Magick.NET/files/4018351/Dockerfile.txt)

[06:22:59 ERR] The type initializer for 'NativeMagickSettings' threw an exception.
System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libMagick.Native-Q16-x64.dll: No such file or directory
at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
at ImageMagick.Environment.NativeEnvironment.Initialize()
at ImageMagick.Environment.Initialize()
at ImageMagick.MagickSettings.NativeMagickSettings..cctor()
at ImageMagick.MagickSettings.NativeMagickSettings..ctor()
at ImageMagick.MagickSettings..ctor()
at ImageMagick.MagickImage..ctor()
at ImageMagick.MagickImage..ctor(Byte[] data)

**Comment by dlemstra** [comment]
You don't need to install ImageMagick this comes with the library. And this fails because you are using the `alpine` version of the image and that does not comes with the required bits to run Magick.Native library. You can find a solution for this in #523.

**Comment by NagaRajeshK** [comment]
Thank you dlemstra. I changed the alpine image then it worked.
