### ISSUE TITLE
SVG memory allocation failed

### ISSUE THREAD

**Issue by jbrockerville** [dlemstra/Magick.NET#999]
### Description

```
ImageMagick.MagickResourceLimitErrorException: memory allocation failed `data.svg' @ error/svg.c/RenderRSVGImage/565
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /_/src/Magick.NET/Native/NativeInstance.cs:line 57
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings`1 settings) in /_/src/Magick.NET/Native/MagickImage.cs:line 5307
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings, Boolean ping) in /_/src/Magick.NET/MagickImage.cs:line 7252
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings) in /_/src/Magick.NET/MagickImage.cs:line 5070
   at ImageMagick.MagickImage.Read(String fileName) in /_/src/Magick.NET/MagickImage.cs:line 5031
   at ImageMagick.MagickImage..ctor(String fileName) in /_/src/Magick.NET/MagickImage.cs:line 222
   at malloc.Program.Main(String[] args) in D:\malloc\Program.cs:line 16
```

### Steps to Reproduce

Run the following code with `data.svg` inside [data.zip](https://github.com/dlemstra/Magick.NET/files/6886659/data.zip):
```cs
using ImageMagick;
using System;

namespace malloc
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var file_path = "data.svg";
                MagickFormat imageFormat = new MagickImageInfo(file_path).Format;
                if (imageFormat == MagickFormat.Svg)
                {
                    using var image = new MagickImage(file_path);
                    image.Write("data.jpg", MagickFormat.Jpg);
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }
}
```

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 8.1.0
- Environment (Operating system, version and so on): Windows 10
- Additional information:

**Comment by jbrockerville** [comment]
Well... Upon further experimentation, maybe not an issue. I can enforce a width and height with `MagickReadSettings` and prevent the exception.
